[server]
host = "0.0.0.0"
port = 8080

[log]
level = "info"

[pipeline]
default_pipeline_timeout_secs = 3600
default_node_timeout_secs = 600
fail_fast = true

[redis]
url = "redis://localhost:6379"
password = ""

[rabbitmq]
url = "amqp://localhost:5672"
user = "guest"
password = "guest"

# NEVER INCLUDE THESE IN A GIT REPO
# This is meant as a reference and should be set
# with environment variables in the Jefferies deployment
# [github]
# app_id = ""
# webhook_secret = ""
# client_id = ""
# client_secret = ""
# private_key = ""
